name: Notificar Projetos Pais
on:
  push:
    branches:
      - main
    paths:
      - 'src/registry/**'

jobs:
  notificar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repositorios:
          - cristhianmachado/sistema-principal
          - cristhianmachado/painel-admin
          
    steps:
      - name: Avisar ${{ matrix.repositorios }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ matrix.repositorios }}
          event-type: atualizou-componente